name: publish-engines

on:
  repository_dispatch:
    types:
      - publish-engines

jobs:
  cli-commands:
    timeout-minutes: 10
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v2-beta
        with:
          node-version: '12'
          check-latest: true
      - run: npm i --silent -g pnpm@5.1.7 --unsafe-perm
      - run: pnpm i --no-prefer-frozen-lockfile --reporter=silent --ignore-scripts
      - run: pnpm run publish-all
        env:
          CI: true
          GITHUB_EVENT_CLIENT_PAYLOAD: ${{ toJson(github.event.client_payload) }}
          NPM_TOKEN: ${{ secrets.NPM_TOKEN }}
          - uses: stefanzweifel/git-auto-commit-action@v4
          with:
            # Optional but recommended, defaults to "Apply automatic changes"
            commit_message: ${{ github.event.client_payload.commit }}
        
            # Optional commit user and author settings
            commit_user_name: prisma-bot
            commit_user_email: suchanek@prisma.io
            commit_author: Prismo <suchanek@prisma.io>
