name: publish-engines

on:
  repository_dispatch:
    types:
      - publish-engines

jobs:
  cli-commands:
    timeout-minutes: 10
    runs-on: ubuntu-latest

    steps:
      - uses: actions/setup-node@v2
        with:
          node-version: '12'
          check-latest: true
      - run: bash .github/workflows/setup.sh
        env:
          CI: true
          GITHUB_CONTEXT: ${{ toJson(github) }}

      - run: pnpm run publish-all
        env:
          CI: true
          GITHUB_CONTEXT: ${{ toJson(github) }}
