name: publish-engines

on:
  repository_dispatch:
    types:
      - publish-engines

jobs:
  cli-commands:
    timeout-minutes: 10
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v2-beta
        with:
          node-version: '12'
          check-latest: true
      - run: npm i --silent -g pnpm@5.1.7 --unsafe-perm
      - run: pnpm i --no-prefer-frozen-lockfile --reporter=silent --ignore-scripts
      - run: pnpm run publish-all
        env:
          CI: true
          GITHUB_EVENT: ${{ toJson(github.event) }}
